<?php

namespace frontend\components;

use yii\base\Widget;
use yii\helpers\Html;

class RctreplyWidget extends \yii\base\Widget
{
    public $recent_dis;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $dis_str = '';

        foreach ($this->recent_dis as $rct_di) {
            $dis_str .= '<div class="post">' .
                '<div class="title">' .
                '<p style="color: #777777;font-family: italic;">' .
                nl2br($rct_di->content) . '</p>' .
                '<p class="text"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>' . Html::encode($rct_di->user->username) . ' (' . date('Y-m-d H:i:s', $rct_di->created_at) . ')</p>' .
//                '<p style="font-size: 8pt;color: blue"> 《<a href="11111">' . Html::encode(111111111) . '</a>》</p>' .
                '<hr></div></div>';
        }

        return $dis_str;
    }
}